sudo: required
language: python
python:
- 3.6.6
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - pip install -r requirements.txt
script:
  - python -W ignore -m unittest discover
