name: datamart_env
dependencies:
  - ca-certificates=2018.03.07=0
  - certifi=2018.8.24=py36_1
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - ncurses=6.1
  - openssl=1.0.2p
  - pip=10.0.1
  - python=3.6.6
  - readline=7.0
  - setuptools=40.2.0=py36_0
  - sqlite=3.24.0
  - tk=8.6.8
  - wheel=0.31.1=py36_0
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - numpy==1.15.2
    - pandas==0.22.0
    - python-dateutil==2.7.3
    - pytz==2018.5
    - six==1.11.0